<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.Ares-XI</groupId>
    <artifactId>byteops</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>modules/api-boot</module>
        <module>modules/api-modify</module>
        <module>modules/GammaX-test-agent</module>
        <module>modules/GammaX-test-plugin</module>
    </modules>

    <properties>
        <java.version>9</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>
</project>