/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_gammax_internal_util_ClassLoaderExtend */

#ifndef _Included_io_gammax_internal_util_ClassLoaderExtend
#define _Included_io_gammax_internal_util_ClassLoaderExtend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_gammax_internal_util_ClassLoaderExtend
 * Method:    defineClass
 * Signature: (Ljava/lang/ClassLoader;Ljava/lang/String;[BIILjava/security/ProtectionDomain;)V
 */
JNIEXPORT void JNICALL Java_io_gammax_internal_util_ClassLoaderExtend_defineClass
  (JNIEnv *, jclass, jobject, jstring, jbyteArray, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
